branch-defaults:
  master:
    environment: prGroupme-env
global:
  application_name: pr-groupme
  default_ec2_keyname: kp1
  default_platform: 64bit Amazon Linux 2016.09 v3.3.0 running Node.js
  default_region: us-east-1
  profile: null
  sc: git
